### PR TITLE
Added more stuff

### PR DESCRIPTION
**Pull request by XFizzer**
Added
 - Player Visibility on/off
 - players won't get hungry anymore

Tested and works👍🏻

### CODE REVIEW

**Comment by Enrick3344** [comment]
@XFizzer Check your Emails ;)

**Comment by Enrick3344** [comment]
added ya as collaborator ;P

**Comment by XFizzer** [comment]
@Enrick3344 Thanks😄

**Comment by Enrick3344** [comment]
@XFizzer Np:) You're helping alot ;P

**Pull request merged**
